/* Column Constraints

Four supported constraint types:

1. Not Null
2. Unique
3. Primary Key
4. Foreign Key

*** The only enforced constraint is "Not Null"
*/

CREATE DATABASE CONSTRAINT_DEMO;

CREATE SCHEMA CONSTRAINT_DEMO.SQL;

-- 1. NOT NULL
CREATE OR REPLACE TABLE CONSTRAINT_DEMO.SQL.ORDERS
(O_ORDERKEY NUMBER(38,0),
O_CUSTKEY NUMBER(38,0),
O_ORDERSTATUS VARCHAR(1) NOT NULL,
O_TOTALPRICE NUMBER(12,2),
O_ORDERDATE DATE,
O_ORDERPRIORITY VARCHAR(15),
O_CLERK VARCHAR(15),
O_SHIPPRIORITY NUMBER(38,0),
O_COMMENT VARCHAR
)
;


-- NOT NULL is enforced.
INSERT INTO
CONSTRAINT_DEMO.SQL.ORDERS
VALUES
(3011172,65, NULL,67802.72,'1997-07-14','5-LOW','Clerk#000000926',0,'foxes cajole bold deposits. furiously even Tiresias wake carefully. special in')
;



-- Validate the result.
SELECT *
FROM CONSTRAINT_DEMO.SQL.ORDERS;

-- SHOW TABLES does not work here ;(
-- Display the table DDL.
SELECT GET_DDL('table', 'CONSTRAINT_DEMO.SQL.ORDERS');



INSERT INTO
CONSTRAINT_DEMO.SQL.ORDERS
VALUES
(3011172,65, 'O',67802.72,'1997-07-14','5-LOW','Clerk#000000926',0,'foxes cajole bold deposits. furiously even Tiresias wake carefully. special in')
;



/*
The next 3 constraints.

2. Unique
3. Primary Key
4. Foreign Key

Can be defined inline or out-of-line.
With or without a constraint name.

*/



-- 2. UNIQUE constraint
CREATE OR REPLACE TABLE CONSTRAINT_DEMO.SQL.ORDERS
(O_ORDERKEY NUMBER(38,0),
O_CUSTKEY NUMBER(38,0),
O_ORDERSTATUS VARCHAR(1) UNIQUE,
O_TOTALPRICE NUMBER(12,2),
O_ORDERDATE DATE,
O_ORDERPRIORITY VARCHAR(15),
O_CLERK VARCHAR(15),
O_SHIPPRIORITY NUMBER(38,0),
O_COMMENT VARCHAR
)
;




INSERT INTO
CONSTRAINT_DEMO.SQL.ORDERS
VALUES
(3011172,65,'O',67802.72,'1997-07-14','5-LOW','Clerk#000000926',0,'foxes cajole bold deposits. furiously even Tiresias wake carefully. special in'),
(3011172,65,'O',67802.72,'1997-07-14','5-LOW','Clerk#000000926',0,'foxes cajole bold deposits. furiously even Tiresias wake carefully. special in')
;




-- Uniqueness is not enforced.
SELECT *
FROM CONSTRAINT_DEMO.SQL.ORDERS;





-- Syntax with a constraint name.
CREATE OR REPLACE TABLE CONSTRAINT_DEMO.SQL.ORDERS
(O_ORDERKEY NUMBER(38,0),
O_CUSTKEY NUMBER(38,0),
O_ORDERSTATUS VARCHAR(1) CONSTRAINT unique_order_status UNIQUE,
O_TOTALPRICE NUMBER(12,2),
O_ORDERDATE DATE,
O_ORDERPRIORITY VARCHAR(15),
O_CLERK VARCHAR(15),
O_SHIPPRIORITY NUMBER(38,0),
O_COMMENT VARCHAR
)
;



--Check DDL
SELECT GET_DDL('table', 'CONSTRAINT_DEMO.SQL.ORDERS');





-- Out-of-line syntax.
CREATE OR REPLACE TABLE CONSTRAINT_DEMO.SQL.ORDERS
(O_ORDERKEY NUMBER(38,0),
O_CUSTKEY NUMBER(38,0),
O_ORDERSTATUS VARCHAR(1),
O_TOTALPRICE NUMBER(12,2),
O_ORDERDATE DATE,
O_ORDERPRIORITY VARCHAR(15),
O_CLERK VARCHAR(15),
O_SHIPPRIORITY NUMBER(38,0),
O_COMMENT VARCHAR,
CONSTRAINT unique_os UNIQUE (O_ORDERSTATUS)
)
;





--Multiple unique constraints by an out-of-line constraint
CREATE OR REPLACE TABLE CONSTRAINT_DEMO.SQL.ORDERS
(O_ORDERKEY NUMBER(38,0),
O_CUSTKEY NUMBER(38,0),
O_ORDERSTATUS VARCHAR(1),
O_TOTALPRICE NUMBER(12,2),
O_ORDERDATE DATE,
O_ORDERPRIORITY VARCHAR(15),
O_CLERK VARCHAR(15),
O_SHIPPRIORITY NUMBER(38,0),
O_COMMENT VARCHAR,
CONSTRAINT unique_columns UNIQUE (O_ORDERKEY, O_CUSTKEY, O_ORDERSTATUS)
)
;




-- 3. PRIMARY KEY


-- Inline syntax.
CREATE OR REPLACE TABLE CONSTRAINT_DEMO.SQL.ORDERS
(O_ORDERKEY NUMBER(38,0) CONSTRAINT order_pk PRIMARY KEY,
O_CUSTKEY NUMBER(38,0),
O_ORDERSTATUS VARCHAR(1),
O_TOTALPRICE NUMBER(12,2),
O_ORDERDATE DATE,
O_ORDERPRIORITY VARCHAR(15),
O_CLERK VARCHAR(15),
O_SHIPPRIORITY NUMBER(38,0),
O_COMMENT VARCHAR)
;


--Table details
DESC TABLE CONSTRAINT_DEMO.SQL.ORDERS;


--Check DDL
SELECT GET_DDL('table', 'CONSTRAINT_DEMO.SQL.ORDERS');


--Let's see what the PK constraint does
INSERT INTO
CONSTRAINT_DEMO.SQL.ORDERS
VALUES
(3011172,65,'O',67802.72,'1997-07-14','5-LOW','Clerk#000000926',0,'foxes cajole bold deposits. furiously even Tiresias wake carefully. special in'),
(3011172,65,'O',67802.72,'1997-07-14','5-LOW','Clerk#000000926',0,'foxes cajole bold deposits. furiously even Tiresias wake carefully. special in')
;




--Validate
SELECT *
FROM CONSTRAINT_DEMO.SQL.ORDERS;




-- PRIMARY KEY is informational and is not enforced by Snowflake.



--Primary Key cann not be null
INSERT INTO
CONSTRAINT_DEMO.SQL.ORDERS
VALUES
(null,65,'O',67802.72,'1997-07-14','5-LOW','Clerk#000000926',0,'foxes cajole bold deposits. furiously even Tiresias wake carefully. special in')
;



--2. Out-of-line syntax
CREATE OR REPLACE TABLE CONSTRAINT_DEMO.SQL.ORDERS
(O_ORDERKEY NUMBER(38,0),
O_CUSTKEY NUMBER(38,0),
O_ORDERSTATUS VARCHAR(1),
O_TOTALPRICE NUMBER(12,2),
O_ORDERDATE DATE,
O_ORDERPRIORITY VARCHAR(15),
O_CLERK VARCHAR(15),
O_SHIPPRIORITY NUMBER(38,0),
O_COMMENT VARCHAR,
CONSTRAINT my_pk PRIMARY KEY (O_ORDERKEY)
)
;






--Composite primary key
CREATE OR REPLACE TABLE CONSTRAINT_DEMO.SQL.ORDERS
(O_ORDERKEY NUMBER(38,0),
O_CUSTKEY NUMBER(38,0),
O_ORDERSTATUS VARCHAR(1),
O_TOTALPRICE NUMBER(12,2),
O_ORDERDATE DATE,
O_ORDERPRIORITY VARCHAR(15),
O_CLERK VARCHAR(15),
O_SHIPPRIORITY NUMBER(38,0),
O_COMMENT VARCHAR,
CONSTRAINT order_pks PRIMARY KEY (O_ORDERKEY, O_ORDERDATE)
)
;



--Validate
DESC TABLE CONSTRAINT_DEMO.SQL.ORDERS;


--Can't define composite PKs with inline syntax
CREATE OR REPLACE TABLE CONSTRAINT_DEMO.SQL.ORDERS
(O_ORDERKEY NUMBER(38,0) PRIMARY KEY,
O_CUSTKEY NUMBER(38,0) PRIMARY KEY,
O_ORDERSTATUS VARCHAR(1),
O_TOTALPRICE NUMBER(12,2),
O_ORDERDATE DATE,
O_ORDERPRIORITY VARCHAR(15),
O_CLERK VARCHAR(15),
O_SHIPPRIORITY NUMBER(38,0),
O_COMMENT VARCHAR
)
;





--4. Foreign key syntax (inline)
CREATE OR REPLACE TABLE CONSTRAINT_DEMO.SQL.ORDERS
(O_ORDERKEY NUMBER(38,0),
O_CUSTKEY NUMBER(38,0) CONSTRAINT CUSTOMER_fk FOREIGN KEY REFERENCES CONSTRAINT_DEMO.SQL.CUSTOMER(C_CUSTKEY),
O_ORDERSTATUS VARCHAR(1),
O_TOTALPRICE NUMBER(12,2),
O_ORDERDATE DATE,
O_ORDERPRIORITY VARCHAR(15),
O_CLERK VARCHAR(15),
O_SHIPPRIORITY NUMBER(38,0),
O_COMMENT VARCHAR,
CONSTRAINT my_pk PRIMARY KEY (O_ORDERKEY)
)
;


--The referenced table must exist
CREATE OR REPLACE TABLE CONSTRAINT_DEMO.SQL.CUSTOMER (
	C_CUSTKEY NUMBER(38,0) NOT NULL CONSTRAINT custkey_pk PRIMARY KEY, --the column and the pk constraint 
	C_NAME VARCHAR(25) NOT NULL,
	C_ADDRESS VARCHAR(40) NOT NULL,
	C_NATIONKEY NUMBER(38,0) NOT NULL,
	C_PHONE VARCHAR(15) NOT NULL,
	C_ACCTBAL NUMBER(12,2) NOT NULL,
	C_MKTSEGMENT VARCHAR(10),
	C_COMMENT VARCHAR(117)
);


--Validate
SELECT GET_DDL('table', 'CONSTRAINT_DEMO.SQL.ORDERS');


--Foreign key syntax (out-of-line)
CREATE OR REPLACE TABLE CONSTRAINT_DEMO.SQL.ORDERS
(O_ORDERKEY NUMBER(38,0),
O_CUSTKEY NUMBER(38,0) ,
O_ORDERSTATUS VARCHAR(1),
O_TOTALPRICE NUMBER(12,2),
O_ORDERDATE DATE,
O_ORDERPRIORITY VARCHAR(15),
O_CLERK VARCHAR(15),
O_SHIPPRIORITY NUMBER(38,0),
O_COMMENT VARCHAR,
CONSTRAINT orderkey_pk PRIMARY KEY (O_ORDERKEY),
CONSTRAINT custkey_fk FOREIGN KEY (O_CUSTKEY) REFERENCES CONSTRAINT_DEMO.SQL.CUSTOMER(C_CUSTKEY)
)
;



--Foreign Key is not enforced
INSERT INTO
CONSTRAINT_DEMO.SQL.ORDERS
VALUES
(3011172,65,'O',67802.72,'1997-07-14','5-LOW','Clerk#000000926',0,'foxes cajole bold deposits. furiously even Tiresias wake carefully. special in')
;



--Validate
SELECT *
FROM CONSTRAINT_DEMO.SQL.ORDERS;


SELECT *
FROM CONSTRAINT_DEMO.SQL.CUSTOMER;



/* best practices */

--Add NOT ENFORCED for pk, fk, and unique constraints

CREATE OR REPLACE TABLE CONSTRAINT_DEMO.SQL.ORDERS
(O_ORDERKEY NUMBER(38,0),
O_CUSTKEY NUMBER(38,0),
O_ORDERSTATUS VARCHAR(1),
O_TOTALPRICE NUMBER(12,2),
O_ORDERDATE DATE,
O_ORDERPRIORITY VARCHAR(15),
O_CLERK VARCHAR(15),
O_SHIPPRIORITY NUMBER(38,0),
O_COMMENT VARCHAR,
CONSTRAINT orderkey_pk PRIMARY KEY (O_ORDERKEY) NOT ENFORCED,
CONSTRAINT custkey_fk FOREIGN KEY (O_CUSTKEY) REFERENCES CONSTRAINT_DEMO.SQL.CUSTOMER(C_CUSTKEY) NOT ENFORCED,
CONSTRAINT unique_oderstatus UNIQUE (O_ORDERSTATUS) NOT ENFORCED
)
;





--Use constraint names
CREATE OR REPLACE TABLE CONSTRAINT_DEMO.SQL.ORDERS
(O_ORDERKEY NUMBER(38,0),
O_CUSTKEY NUMBER(38,0),
O_ORDERSTATUS VARCHAR(1),
O_TOTALPRICE NUMBER(12,2),
O_ORDERDATE DATE,
O_ORDERPRIORITY VARCHAR(15),
O_CLERK VARCHAR(15),
O_SHIPPRIORITY NUMBER(38,0),
O_COMMENT VARCHAR,
CONSTRAINT order_pk PRIMARY KEY (O_ORDERKEY),
CONSTRAINT unique_cols UNIQUE(O_CLERK, O_COMMENT)
)
;



CREATE OR REPLACE TABLE CONSTRAINT_DEMO.SQL.ORDERS
(O_ORDERKEY NUMBER(38,0),
O_CUSTKEY NUMBER(38,0),
O_ORDERSTATUS VARCHAR(1),
O_TOTALPRICE NUMBER(12,2),
O_ORDERDATE DATE,
O_ORDERPRIORITY VARCHAR(15),
O_CLERK VARCHAR(15),
O_SHIPPRIORITY NUMBER(38,0),
O_COMMENT VARCHAR,
PRIMARY KEY (O_ORDERKEY),
UNIQUE(O_CLERK, O_COMMENT)
)
;


/* Cleanup */
SHOW TABLES IN CONSTRAINT_DEMO.SQL;

DROP DATABASE CONSTRAINT_DEMO;
