-- =====================================================================
-- DoD2026 Snowflake demo: Provision the role, warehouse, database, schema,
-- and service user.
-- DoD2026_Demo replaces the {{DOD2026_PAT_NAME}} placeholder.
-- =====================================================================

-- 1. Create the network policy as SECURITYADMIN.
USE ROLE SECURITYADMIN;

CREATE NETWORK POLICY IF NOT EXISTS DOD2026_NETWORK_POLICY
	ALLOWED_IP_LIST = ('0.0.0.0/0')
	COMMENT = 'Demo policy for programmatic access; restrict in production';

-- 2. Create the role and user as USERADMIN.
USE ROLE USERADMIN;

CREATE ROLE IF NOT EXISTS DOD_DEVELOPER
	COMMENT = 'Demo role for DoD2026 Snowflake tests';

CREATE OR REPLACE USER DOD2026_USER
	DEFAULT_ROLE = DOD_DEVELOPER
	DEFAULT_WAREHOUSE = DOD_WAREHOUSE
	DEFAULT_NAMESPACE = DOD2026_DB.DOD2026_DEMO
	TYPE = SERVICE
	COMMENT = 'Service user for DoD2026 tests';

GRANT ROLE DOD_DEVELOPER TO USER DOD2026_USER;

ALTER USER DOD2026_USER SET NETWORK_POLICY = DOD2026_NETWORK_POLICY;

-- Add the custom role beneath SYSADMIN in the role hierarchy.
GRANT ROLE DOD_DEVELOPER TO ROLE SYSADMIN;

-- 3. Create the objects as SYSADMIN.
USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS DOD_WAREHOUSE
	WAREHOUSE_SIZE = XSMALL
	AUTO_SUSPEND = 60
	AUTO_RESUME = TRUE
	INITIALLY_SUSPENDED = TRUE
	MIN_CLUSTER_COUNT = 1
	MAX_CLUSTER_COUNT = 1
	COMMENT = 'Demo warehouse for DoD2026 Snowflake tests';

CREATE DATABASE IF NOT EXISTS DOD2026_DB
	COMMENT = 'Demo database for DoD2026 Snowflake tests';

CREATE SCHEMA IF NOT EXISTS DOD2026_DB.DOD2026_DEMO
	COMMENT = 'Demo schema for DoD2026 Snowflake tests';

-- 4. Grant privileges to the demo role.
GRANT USAGE ON WAREHOUSE DOD_WAREHOUSE TO ROLE DOD_DEVELOPER;
GRANT OPERATE ON WAREHOUSE DOD_WAREHOUSE TO ROLE DOD_DEVELOPER;

GRANT USAGE ON DATABASE DOD2026_DB TO ROLE DOD_DEVELOPER;
GRANT USAGE ON SCHEMA DOD2026_DB.DOD2026_DEMO TO ROLE DOD_DEVELOPER;
GRANT CREATE TABLE ON SCHEMA DOD2026_DB.DOD2026_DEMO TO ROLE DOD_DEVELOPER;
GRANT CREATE HYBRID TABLE ON SCHEMA DOD2026_DB.DOD2026_DEMO TO ROLE DOD_DEVELOPER;
GRANT CREATE VIEW ON SCHEMA DOD2026_DB.DOD2026_DEMO TO ROLE DOD_DEVELOPER;
GRANT CREATE SEQUENCE ON SCHEMA DOD2026_DB.DOD2026_DEMO TO ROLE DOD_DEVELOPER;
GRANT CREATE STAGE ON SCHEMA DOD2026_DB.DOD2026_DEMO TO ROLE DOD_DEVELOPER;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA DOD2026_DB.DOD2026_DEMO TO ROLE DOD_DEVELOPER;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA DOD2026_DB.DOD2026_DEMO TO ROLE DOD_DEVELOPER;

-- 5. Create a role-restricted programmatic access token.
USE ROLE USERADMIN;

ALTER USER DOD2026_USER ADD PROGRAMMATIC ACCESS TOKEN {{DOD2026_PAT_NAME}}
	DAYS_TO_EXPIRY = 30
	ROLE_RESTRICTION = 'DOD_DEVELOPER'
	COMMENT = 'DoD2026 demo token with a 30-day lifetime';

-- 6. Validate the environment.
SHOW WAREHOUSES LIKE 'DOD_WAREHOUSE';
SHOW DATABASES LIKE 'DOD2026_DB';
SHOW GRANTS TO ROLE DOD_DEVELOPER;
